backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: 'services'
    label: 'services'
    folder: 'src/content/services'
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "service"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "weight", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
